=== Agh42/verinice-veo/veo-rest/src/test/resources/testentity/person.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "_self": {
      "type": "string",
      "description": "A valid reference to this resource.",
      "readOnly": true,
      "format": "uri"
    },
    "abbreviation": {
      "type": "string",
      "description": "The abbreviation for the Element.",
      "maxLength": 255
    },
    "createdAt": {
      "type": "string",
      "description": "A timestamp acc. to RFC 3339 specifying when this entity was created.",
      "readOnly": true
    },
    "createdBy": {
      "type": "string",
      "description": "The username of the user who created this object.",
      "readOnly": true
    },
    "customAspects": {
      "type": "object",
      "title": "CustomAspect",
      "description": "Groups of customizable attributes - see '/schemas'",
      "properties": {
        "person_generalInformation": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "id": {
              "type": "string",
              "title": "The UUID to identify the element",
              "format": "regex",
              "pattern": "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
            },
            "applicableTo": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "domains": {
              "type": "array",
              "title": "The list of domains in which this element is present.",
              "description": "The ids of elements of the type domain.",
              "items": {
                "type": "object",
                "properties": {
                  "displayName": {
                    "type": "string",
                    "description": "A friendly human readable title of the referenced domain."
                  },
                  "targetUri": {
                    "type": "string",
                    "description": "The resource URL of the referenced domain."
                  }
                },
                "required": [
                  "targetUri"
                ]
              },
              "uniqueItems": true
            },
            "references": {
              "type": "array",
              "items": {
                "properties": {
                  "displayName": {
                    "type": "string",
                    "description": "A friendly human readable title of the referenced object."
                  },
                  "targetUri": {
                    "type": "string",
                    "description": "The resource URL of the referenced object."
                  }
                },
                "required": [
                  "targetUri"
                ]
              }
            },
            "attributes": {
              "type": "object",
              "properties": {
                "person_generalInformation_salutation": {
                  "type": "string"
                },
                "person_generalInformation_title": {
                  "type": "string"
                },
                "person_generalInformation_givenName": {
                  "type": "string"
                },
                "person_generalInformation_familyName": {
                  "type": "string"
                }
              }
            }
          }
        },
        "person_contactInformation": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "id": {
              "type": "string",
              "title": "The UUID to identify the element",
              "format": "regex",
              "pattern": "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
            },
            "applicableTo": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "domains": {
              "type": "array",
              "title": "The list of domains in which this element is present.",
              "description": "The ids of elements of the type domain.",
              "items": {
                "type": "object",
                "properties": {
                  "displayName": {
                    "type": "string",
                    "description": "A friendly human readable title of the referenced domain."
                  },
                  "targetUri": {
                    "type": "string",
                    "description": "The resource URL of the referenced domain."
                  }
                },
                "required": [
                  "targetUri"
                ]
              },
              "uniqueItems": true
            },
            "references": {
              "type": "array",
              "items": {
                "properties": {
                  "displayName": {
                    "type": "string",
                    "description": "A friendly human readable title of the referenced object."
                  },
                  "targetUri": {
                    "type": "string",
                    "description": "The resource URL of the referenced object."
                  }
                },
                "required": [
                  "targetUri"
                ]
              }
            },
            "attributes": {
              "type": "object",
              "properties": {
                "person_contactInformation_office": {
                  "type": "string"
                },
                "person_contactInformation_mobile": {
                  "type": "string"
                },
                "person_contactInformation_private": {
                  "type": "string"
                },
                "person_contactInformation_fax": {
                  "type": "string"
                },
                "person_contactInformation_email": {
                  "type": "string"
                },
                "person_contactInformation_website": {
                  "type": "string",
                  "format": "uri",
                  "pattern": "^(https?|ftp)://"
                }
              }
            }
          }
        },
        "person_dataProtectionOfficer": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "id": {
              "type": "string",
              "title": "The UUID to identify the element",
              "format": "regex",
              "pattern": "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
            },
            "applicableTo": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "domains": {
              "type": "array",
              "title": "The list of domains in which this element is present.",
              "description": "The ids of elements of the type domain.",
              "items": {
                "type": "object",
                "properties": {
                  "displayName": {
                    "type": "string",
                    "description": "A friendly human readable title of the referenced domain."
                  },
                  "targetUri": {
                    "type": "string",
                    "description": "The resource URL of the referenced domain."
                  }
                },
                "required": [
                  "targetUri"
                ]
              },
              "uniqueItems": true
            },
            "references": {
              "type": "array",
              "items": {
                "properties": {
                  "displayName": {
                    "type": "string",
                    "description": "A friendly human readable title of the referenced object."
                  },
                  "targetUri": {
                    "type": "string",
                    "description": "The resource URL of the referenced object."
                  }
                },
                "required": [
                  "targetUri"
                ]
              }
            },
            "attributes": {
              "type": "object",
              "properties": {
                "person_dataProtectionOfficer_expertise": {
                  "type": "boolean"
                },
                "person_dataProtectionOfficer_profession": {
                  "type": "string"
                }
              }
            }
          }
        },
        "person_address": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "id": {
              "type": "string",
              "title": "The UUID to identify the element",
              "format": "regex",
              "pattern": "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
            },
            "applicableTo": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "domains": {
              "type": "array",
              "title": "The list of domains in which this element is present.",
              "description": "The ids of elements of the type domain.",
              "items": {
                "type": "object",
                "properties": {
                  "displayName": {
                    "type": "string",
                    "description": "A friendly human readable title of the referenced domain."
                  },
                  "targetUri": {
                    "type": "string",
                    "description": "The resource URL of the referenced domain."
                  }
                },
                "required": [
                  "targetUri"
                ]
              },
              "uniqueItems": true
            },
            "references": {
              "type": "array",
              "items": {
                "properties": {
                  "displayName": {
                    "type": "string",
                    "description": "A friendly human readable title of the referenced object."
                  },
                  "targetUri": {
                    "type": "string",
                    "description": "The resource URL of the referenced object."
                  }
                },
                "required": [
                  "targetUri"
                ]
              }
            },
            "attributes": {
              "type": "object",
              "properties": {
                "person_address_address1": {
                  "type": "string"
                },
                "person_address_address2": {
                  "type": "string"
                },
                "person_address_postcode": {
                  "type": "string"
                },
                "person_address_city": {
                  "type": "string"
                },
                "person_address_country": {
                  "type": "string"
                },
                "person_address_state": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "description": {
      "type": "string",
      "description": "The description for the Element.",
      "maxLength": 65535
    },
    "designator": {
      "type": "string",
      "description": "Compact human-readable identifier that is unique within the client.",
      "readOnly": true
    },
    "domains": {
      "type": "object",
      "description": "Details about this element's association with domains. Domain ID is key, association object is value.",
      "patternProperties": {
        "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$": {
          "properties": {
            "subType": {
              "type": "string",
              "enum": [
                "PER_DataProtectionOfficer",
                "PER_Person"
              ]
            },
            "status": {
              "type": "string"
            }
          },
          "dependantRequired": {
            "subType": [
              "status"
            ],
            "status": [
              "subType"
            ]
          },
          "allOf": [
            {
              "if": {
                "properties": {
                  "subType": {
                    "const": "PER_DataProtectionOfficer"
                  }
                }
              },
              "then": {
                "properties": {
                  "status": {
                    "enum": [
                      "NEW",
                      "IN_PROGRESS",
                      "FOR_REVIEW",
                      "RELEASED",
                      "ARCHIVED"
                    ]
                  }
                }
              }
            },
            {
              "if": {
                "properties": {
                  "subType": {
                    "const": "PER_Person"
                  }
                }
              },
              "then": {
                "properties": {
                  "status": {
                    "enum": [
                      "NEW",
                      "IN_PROGRESS",
                      "FOR_REVIEW",
                      "RELEASED",
                      "ARCHIVED"
                    ]
                  }
                }
              }
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "id": {
      "type": "string",
      "description": "ID must be a valid UUID string following RFC 4122.",
      "format": "uuid"
    },
    "links": {
      "type": "object",
      "title": "CustomLink",
      "description": "Custom relations which do not affect the behavior.",
      "properties": {
        
      }
    },
    "name": {
      "type": "string",
      "description": "The name for the Element.",
      "maxLength": 255
    },
    "owner": {
      "type": "object",
      "properties": {
        "displayName": {
          "type": "string",
          "description": "A friendly human readable title of the referenced unit.",
          "readOnly": true
        },
        "resourcesUri": {
          "type": "string",
          "readOnly": true
        },
        "searchesUri": {
          "type": "string",
          "readOnly": true
        },
        "targetUri": {
          "type": "string",
          "description": "The resource URL of the referenced unit.",
          "format": "uri"
        }
      },
      "required": [
        "targetUri"
      ],
      "description": "A reference to the unit containing this entity."
    },
    "parts": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "displayName": {
            "type": "string",
            "description": "A friendly human readable title of the referenced entity.",
            "readOnly": true
          },
          "resourcesUri": {
            "type": "string",
            "readOnly": true
          },
          "searchesUri": {
            "type": "string",
            "readOnly": true
          },
          "targetUri": {
            "type": "string",
            "description": "The resource URL of the referenced entity.",
            "format": "uri"
          }
        },
        "required": [
          "targetUri"
        ],
        "description": "A reference to an entity's part"
      }
    },
    "type": {
      "type": "string",
      "description": "Entity type identifier",
      "readOnly": true
    },
    "updatedAt": {
      "type": "string",
      "description": "A timestamp acc. to RFC 3339 specifying when this entity was created.",
      "readOnly": true
    },
    "updatedBy": {
      "type": "string",
      "description": "The username of the user who last updated this object.",
      "readOnly": true
    }
  },
  "required": [
    "name",
    "owner"
  ],
  "title": "person",
  "description": "Schema for person"
}

=== Agh42/verinice-veo/k6/tom.json
{
  "owner": {
    "targetUri": "/units/76d22240-5736-4a4d-ac93-a9adc9574bad"
  },
  "domains": {
    
  },
  "description": "Maßnahmen, damit Unbefugten der Zutritt zu den Datenverarbeitungsanlagen verwehrt wird, mit denen personenbezogene Daten verarbeitet werden:\n\n(Beschreibung des Zutrittskontrollsystems, z.B. Ausweisleser, kontrollierte Schlüsselvergabe, etc. Siehe Checkliste TOM Zutrittskontrolle)",
  "name": "Zutrittskontrolle",
  "abbreviation": "TOM-1",
  "customAspects": {
    "control_implementation": {
        "domains": [],
        "attributes": {
            "control_implementation_date": "2022-11-30"
        }
    },
    "control_dataProtection": {
        "domains": [],
        "attributes": {
            "control_dataProtection_objectives": [
                "control_dataProtection_objectives_confidentiality",
                "control_dataProtection_objectives_integrity"
            ]
        }
    }
  }
}

=== Agh42/verinice-veo/k6/person.json
{
  "owner": {
    "targetUri": "/units/76d22240-5736-4a4d-ac93-a9adc9574bad"
  },
  "domains": {
    
  },
  "name": "Person (created for k6 load test)",
  "customAspects": {
    "person_generalInformation": {
      "attributes": {
        "person_generalInformation_givenName": "Hans",
        "person_generalInformation_familyName": "Mustermann",
        "person_generalInformation_salutation": "Herr"
      },
      "id": "00000000-0000-0000-0000-000000000000"
    },
    "person_address": {
      "attributes": {
        "person_address_address1": "Hauptstr. 1",
        "person_address_postcode": "10000",
        "person_address_city": "Berlin",
        "person_address_country": "Deutschland"
      },
      "id": "00000000-0000-0000-0000-000000000000"
    },
    "person_contactInformation": {
      "attributes": {
        "person_contactInformation_office": "01511094321",
        "person_contactInformation_email": "dies-ist-keine@email.com"
      },
      "id": "00000000-0000-0000-0000-000000000000"
    }
  }
}

=== Agh42/verinice-veo/k6/scenario.json
{
  "name": "Scenario (created for k6 load test)",
  "abbreviation": "DS-G.33",
  "owner": {
    "targetUri": "https://api.develop.verinice.com/veo/units/UNIT_ID"
  },
  "links": {
    
  },
  "customAspects": {
    "scenario_threat": {
      "domains": [],
      "attributes": {
        "scenario_threat_type": "scenario_threat_type_criminalAct"
      }
    },
    "scenario_generalInformation": {
      "domains": [],
      "attributes": {
        "scenario_generalInformation_document": "https://en.wikipedia.org/wiki/Special:Random"
      }
    },
    "scenario_vulnerability": {
      "domains": [],
      "attributes": {
        "scenario_vulnerability_type": "scenario_vulnerability_type_organisationalDeficiencies"
      }
    }
  },
  "type": "scenario",
  "parts": [],
  "domains": {
    "DOMAIN_ID": {
      "subType": "SCN_Scenario",
      "status": "IN_PROGRESS",
      "riskValues": {
        "DSRA": {
          "potentialProbability": "PROBABILITY"
        }
      }
    }
  }
}

=== Agh42/verinice-veo/k6/joint_controller.json
{
  "owner": {
    "targetUri": "/units/76d22240-5736-4a4d-ac93-a9adc9574bad"
  },
  "domains": {},
  "name": "Joint controller (created for k6 load test)",
  "customAspects": {
    "scope_address": {
      "attributes": {
        "scope_address_address1": "Musterstr. 1",
        "scope_address_postcode": "12345",
        "scope_address_city": "Berlin",
        "scope_address_country": "Deutschland"
      },
      "id": "00000000-0000-0000-0000-000000000000"
    },
    "scope_contactInformation": {
      "attributes": {
        "scope_contactInformation_phone": "0151123456789",
        "scope_contactInformation_email": "no-real-email@email.invalid"
      },
      "id": "00000000-0000-0000-0000-000000000000"
    }
  }
}

=== Agh42/verinice-veo/k6/responsible_body.json
{
  "owner": {
    "targetUri": "/units/76d22240-5736-4a4d-ac93-a9adc9574bad"
  },
  "designator": "",
  "domains": {
    "774e14f3-a8a8-4f22-aa1d-4344ac39517b": {
      
    }
  },
  "name": "Verantwortliche Stelle",
  "customAspects": {
    "scope_address": {
      "attributes": {
        "scope_address_address1": "Musterstr. 1",
        "scope_address_postcode": "12345",
        "scope_address_city": "Berlin",
        "scope_address_country": "Deutschland"
      },
      "id": "00000000-0000-0000-0000-000000000000",
      "type": "scope_address"
    },
    "scope_contactInformation": {
      "attributes": {
        "scope_contactInformation_phone": "0151123456789",
        "scope_contactInformation_email": "no-real-email@email.invalid"
      },
      "id": "00000000-0000-0000-0000-000000000000",
      "type": "scope_contactInformation"
    }
  }
}
